sonar.projectKey=geckoal_gecko-iot-client
sonar.organization=geckoal

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=Gecko IoT Client
sonar.projectVersion=0.1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=gecko_iot_client/src
sonar.tests=gecko_iot_client/tests

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Language
sonar.language=py

# Coverage and test results
sonar.python.coverage.reportPaths=gecko_iot_client/coverage.xml
sonar.python.xunit.reportPath=gecko_iot_client/test-results.xml

# Exclusions
sonar.exclusions=**/__pycache__/**,**/.*,**/*.egg-info/**,**/build/**,**/docs/**
sonar.test.exclusions=**/tests/**
sonar.coverage.exclusions=**/tests/**,**/examples/**,**/__pycache__/**

# Python specific
sonar.python.pylint.reportPaths=
sonar.python.bandit.reportPaths=